repertoire/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.detail import DetailView
from repertoire.views import RepertoireView
from repertoire.models import *

urlpatterns = patterns('',
    url(r'get_playlist/$', 'repertoire.views.generate_playlist', name='get-playlist'),
    url(r'arranger/$', RepertoireView.as_view(), {'filter':'arranger'}, name='by-arranger'),
    url(r'composer/$', RepertoireView.as_view(), {'filter':'composer'}, name='by-composer'),
    url(r'guest/$', RepertoireView.as_view(), {'filter':'guest'}, name='by-guest'),
    url(r'soloist/$', RepertoireView.as_view(), {'filter':'soloist'}, name='by-soloist'),
    url(r'song/$', RepertoireView.as_view(), {'filter':'song'}, name='by-song'),
    url(r'premiere/$', RepertoireView.as_view(), {'filter':'premiere'}, name='by-premiere'),

    #handle individual details per item in repertoire
    url(r'concert/(?P<pk>\d+)/$', DetailView.as_view(model=Concert), name='concert-detail'),
    url(r'performer/(?P<pk>\d+)/$', DetailView.as_view(model=Performer), name='performer-detail'),
    url(r'venue/(?P<pk>\d+)/$', DetailView.as_view(model=Venue), name='venue-detail'),
    url(r'song/(?P<pk>\d+)/$', DetailView.as_view(model=Song), name='song-detail'),
    #TODO Add season detail - what should go there?
    # url(r'season/(?P<pk>\d+)/$', DetailView.as_view(), name='season-detail'),
    # url(r'series/(?P<pk>\d+)/$', DetailView.as_view(model=Series), name='series-detail'),
    url(r'$', RepertoireView.as_view(), name='by-default'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from feincms.content.application.models import ApplicationContent
from feincms.module.page.models import Page
from feincms.module.page.sitemap import PageSitemap
from django.contrib import admin
from django.views.generic.simple import redirect_to
from content.views import BecomeADonor, BecomeASponsor, ProgramAds


admin.autodiscover()

sitemaps = {'pages' : PageSitemap}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cyo.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^audition/', include('auditions.urls')),
    #url(r'^become-a-donor/', BecomeADonor.as_view()),
    #url(r'^become-a-sponsor/', BecomeASponsor.as_view()),
    #url(r'^buy-program-ads/', ProgramAds.as_view()),
    # url(r'^repertoire/', include('repertoire.urls')),
    url(r'repertoire/upload/$', 'repertoire.views.upload_file', name='upload_file'),
    # url(r'^concert/$', redirect_to, {'url' : '/concerts/'}),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
            {'sitemaps': sitemaps}),
    # (r'^search/', include('haystack.urls')),
    url(r'^', include('content.urls')),
    url(r'^', include('feincms.urls')),

)
handler404 = 'content.views.page_not_found'

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

repertoire/models.py
from django.contrib.localflavor.us.models import USStateField
from django.db import models
from django.template.defaultfilters import slugify
from feincms.content.application import models as app_models

# TODO include tagging

CONCERT_SERIES = (
    ('RTO', 'Rock the Orchestra'),
    ('NW', 'New Works'),
    ('MAII', 'Music and Its Industry'),
)

class Series(models.Model):
    """
    This model specifies the concert series. Allowing for future series to be created.
    """
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, blank=True) # should be unique, but causes problems with migration

    class Meta:
        verbose_name_plural = "series"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Series, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    @app_models.permalink
    def get_absolute_url(self):
        return ('concert-archive', 'repertoire.concerts', (), {
            'slug': self.slug,
            })


class Venue(models.Model):
    """
    This table describes the venue for a concert.
    """
    name = models.CharField(max_length=128) #TODO (stephen) once migrations are redone, rename this colmn to title
    address1 = models.CharField(max_length=64, blank=True, null=True)
    address2 = models.CharField(max_length=64, blank=True, null=True)
    city = models.CharField(max_length=60, blank=True, null=True)
    state = USStateField(blank=True, null=True)
    zip_code = models.CharField(max_length=10, blank=True, null=True)

    def __unicode__(self):
            return self.name

    @app_models.permalink
    def get_absolute_url(self):
        return ('venue-detail', 'repertoire.urls', (), {
            'pk': self.pk,
            })


class Concert(models.Model):
    """
    This model stores concert information
    """
    title = models.CharField(max_length=60)
    short_description = models.TextField(verbose_name="Three line descriptor", null=True, blank=True)
    abstract = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    series = models.ForeignKey('Series', blank=True, null=True)
    season = models.IntegerField(blank=True, null=True)

    rough_date = models.CharField(verbose_name="e.g. Summer 2012", max_length=32, blank=True, null=True)
    date_time = models.DateTimeField(blank=True, null=True)

    featured_artist = models.ManyToManyField('Performer', blank=True, null=True) #TODO through PerformedSong?
    venue = models.ForeignKey('Venue', null=True)

    poster_image = models.ImageField(upload_to='concert_poster', blank=True, null=True)
    photos_link = models.URLField( blank=True, null=True)
    video_link = models.URLField( blank=True, null=True)
    program_file = models.FileField(upload_to='concert_program',  blank=True, null=True)

    class Meta:
        ordering = ['date_time']

    def __unicode__(self):
        return self.title

    @app_models.permalink
    def get_absolute_url(self):
        return ('concert-detail', 'repertoire.urls', (), {
            'pk': self.pk,
            })


class PerformedSong(models.Model):
    """
    This table joins Concert and Song
    """
    song = models.ForeignKey('Song')
    concert = models.ForeignKey('Concert', blank=True, null=True)

    arranger = models.ManyToManyField('Performer', related_name='arranger', blank=True, null=True)
    conductor = models.ManyToManyField('Performer', related_name='conductor', blank=True, null=True)
    guest_artist = models.ManyToManyField('Performer', related_name='guest_artist',verbose_name='Guest Artist' ,blank=True,
        null=True)
    soloist = models.ManyToManyField('Performer', blank=True, null=True)

    note = models.TextField(blank=True, null=True)

    PREMIERE_TAGS = (
        ('a','World Premiere'),
        ('b','US Premiere'),
        ('c','Local Premiere'),
        ('d','None'),
    )
    premiere = models.CharField(max_length=1, choices=PREMIERE_TAGS, default='d')

    def __unicode__(self):
        return "%s at %s" % (self.song.title, self.concert.title)


class Song(models.Model):
    """
    This song model stores one song performed by cyo.
    """
    title = models.CharField(max_length=48)
    composer = models.ForeignKey('Performer')
    description = models.TextField('Description of this song', blank=True, null=True)
    audio_file = models.FileField(upload_to='song_audio_file', blank=True, null=True)
    playable = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

    @app_models.permalink
    def get_absolute_url(self):
        return ('song-detail', 'repertoire.urls', (), {
            'pk': self.pk,
            })


class Person(models.Model):
    """
    This model stores artist information
    """
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    birth_year = models.IntegerField(blank=True, null=True)
    death_year = models.IntegerField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Performer(Person):
    @app_models.permalink
    def get_absolute_url(self):
        return ('performer-detail', 'repertoire.urls', (), {
            'pk': self.pk,
            })

class Instrument(models.Model):
    instrument = models.CharField(max_length=32)

    def __unicode__(self):
        return self.instrument

class FeaturedArtistInstrument(models.Model):
    performer = models.ForeignKey('Performer')
    performed_song = models.ForeignKey('PerformedSong')
    instrument = models.ForeignKey('Instrument')

class GuestArtistInstrument(models.Model):
    performer = models.ForeignKey('Performer')
    performed_song = models.ForeignKey('PerformedSong')
    instrument = models.ForeignKey('Instrument')

class SoloistInstrument(models.Model):
    performer = models.ForeignKey('Performer')
    performed_song = models.ForeignKey('PerformedSong')
    instrument = models.ForeignKey('Instrument')
    

repertoire/forms.py
from django import forms
from django.conf import settings
from django.utils.safestring import mark_safe
from repertoire.models import Concert

class TinyMCEEditor(forms.Textarea):

    class Media:
        js = (
            settings.STATIC_URL+'js/jquery.js',
            settings.STATIC_URL+'js/tiny_mce/jscripts/tiny_mce/jquery.tinymce.js',
            )

    def render(self, name, value, attrs=None):
        rendered = super(TinyMCEEditor, self).render(name, value, attrs)
        return rendered + mark_safe(u'''<script type="text/javascript">
    jQuery('#id_%s').tinymce({
        script_url : '%sjs/tiny_mce/tiny_mce.js',
        mode : "none",
        theme : "advanced",
        language : "en",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_buttons1 : "fullscreen,|,formatselect,|,bold,italic,|,sub,sup,|,bullist,numlist,|,anchor,link,unlink,|,code",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_align : "left",
        theme_advanced_path : false,
        theme_advanced_blockformats : "p,h2,h3",
        theme_advanced_resizing : true,
        width:  '680',
        height: '300',
        content_css : "%scss/text.css",
        plugins : "fullscreen,paste",
        paste_auto_cleanup_on_paste : true,
        relative_urls : false
    });
    </script>''' % (name, settings.STATIC_URL, settings.STATIC_URL))

class ConcertForm(forms.ModelForm):
    class Meta:
        model = Concert
        widgets = {
            'description': TinyMCEEditor(),
            'abstract': TinyMCEEditor(),
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()

repertoire/templates/repertoire/_concert_detail.html
{# model = Concert #}
{% autoescape off %}
        {% block main_content %}
                <div><h2>{{ concert.title }}</h2>
                    <h3>Series: <a href="{{ concert.series.get_absolute_url }}">{{ concert.series.title }}</a></h3>
                    <br />  
                    <table>
                        {% for ps in concert.performedsong_set.all %}
                            <tr>
                                <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                <td><a href="{{ ps.song.composer.get_absolute_url}}">{{ ps.song.composer }}</a> <small><em>({{ ps.song.composer.birth_year }}-{% if ps.song.composer.death_year %}{{ ps.song.composer.death_year }}{% else %}Current{% endif %})</em></small></td>
                            </tr>
                        {% endfor %}
                    </table>

                    <br />
                    {{ concert.description|safe }}
                </div>
        {% endblock %}
{% endautoescape %}

repertoire/templates/repertoire/concert_composer_list.html
{% extends 'repertoire/rep_base.html' %}
{# queryset = Performer objects #}
{% block main_content %}
    <h2>Grouped by Composer</h2>

        {% for composer in repertoire_list %}
            <table>
                <thead>
                    <tr class="table-title"><td colspan="2">
                        <h3><a href="{{ composer.get_absolute_url }}">{{ composer.first_name }} {{ composer.last_name }}</a> <small><em>({{ composer.birth_year }}-{% if composer.death_year %}{{ composer.death_year }}{% else %}Current{% endif %})</em></small></h3>
                    </td></tr>
                </thead>
                <tbody>
                {% for song in composer.song_set.all %}
                    {% for ps in song.performedsong_set.all %}
                        <tr>
                            <td><a href="{{ song.get_absolute_url }}">{{ song.title }}</a></td>
                            <td><a href="{{ ps.concert.get_absolute_url }}">{{ ps.concert.title }}</a></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        {% endfor %}

    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
    <br>
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url by-composer %}?page={{ page_obj.previous_page_number }}"><small><em>previous</em></small></a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url by-composer %}?page={{ page_obj.next_page_number }}"><small><em>next</em></small></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

repertoire/templates/repertoire/concert_detail.html
{% extends 'repertoire/rep_base.html' %}
{# model = Concert #}
{% autoescape off %}
        {% block main_content %}
                <div><h2>{{ concert.title }}</h2>
                    <h2><em><small>{{ concert.date_time|date:"l, F jS, Y" }}</small></em></h2>
                    <h3>Series: <a href="{{ concert.series.get_absolute_url }}">{{ concert.series.title }}</a></h3>
                    <br />  
                    <table>
                        {% for ps in concert.performedsong_set.all %}
                            <tr>
                                <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                <td><a href="{{ ps.song.composer.get_absolute_url}}">{{ ps.song.composer }}</a> <small><em>({{ ps.song.composer.birth_year }}-{% if ps.song.composer.death_year %}{{ ps.song.composer.death_year }}{% else %}Current{% endif %})</em></small></td>
                            </tr>
                        {% endfor %}
                    </table>

                    <br />
                    {{ concert.description|safe }}
                </div>
        {% endblock %}
{% endautoescape %}

repertoire/templates/repertoire/concert_list.html
{% extends 'repertoire/rep_base.html' %}
{% block main_content %}
    <h2>Grouped by Concert</h2>

        {% for concert in repertoire_list %}
            <table>
            <thead><tr class="table-title"><td colspan="2"><h3><a href="{{ concert.get_absolute_url }}">{{ concert.title }}</a></h3></td></tr></thead>
                <tbody>
                {% for ps in concert.performedsong_set.all %}

                    <tr>
                        <td><a href="{{ ps.song.get_absolute_url }}">{{ ps.song.title }}</a></td>
                        <td><a href="{{ ps.song.composer.get_absolute_url }}">{{ ps.song.composer }}</a> <small><em>({{ ps.song.composer.birth_year }}-{% if ps.song.composer.death_year %}{{ ps.song.composer.death_year }}{% else %}Current{% endif %})</em></small></td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
        {% endfor %}

    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
    <br>
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url by-default %}?page={{ page_obj.previous_page_number }}"><small><em>previous</em></small></a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url by-default %}?page={{ page_obj.next_page_number }}"><small><em>next</em></small></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

repertoire/templates/repertoire/concert_premiere_list.html
{% extends 'repertoire/rep_base.html' %}
{# queryset = ConcertSong objects #}
{% block main_content %}
    <h2>Premieres</h2>
        <div>
            <table>
                {% for ps in repertoire_list %}
                <tr>
                    <td><a href="{{ ps.song.get_absolute_url }}">{{ ps.song.title }}</a></td>
                    <td><a href="{{ ps.concert.get_absolute_url }}">{{ ps.concert.title }}</a></td>
                    <td>{% if ps.world_premiere %}WP{% endif %}
                        {%  if ps.local_premiere %}USP{% endif %}
                    {%  if ps.local_premiere %}LP{% endif %}</td>
                    <td>{% if ps.concert.date_time %}{{ ps.concert.date_time|date:"M Y"}}
                    {% else %}
                        {{ ps.concert.rough_date }}
                    {% endif %}</td>
                </tr>
                {% endfor %}
            </table>
            {# .... **Now the pagination section** .... #}
            {% if is_paginated %}
            <br>
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% url by-premiere %}?page={{ page_obj.previous_page_number }}"><small><em>previous</em></small></a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{% url by-premiere %}?page={{ page_obj.next_page_number }}"><small><em>next</em></small></a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
{% endblock %}

repertoire/templates/repertoire/concert_song_list.html
{% extends 'repertoire/rep_base.html' %}
{# queryset = Song objects #}
{% block main_content %}
    <h2>Ordered by Song Title</h2>
    <table>
        {% for song in repertoire_list %}
            <tr>
                <td><a href="{{ song.get_absolute_url }}">{{ song.title }}</a></td>
                <td><a href="{{ song.composer.get_absolute_url }}">{{ song.composer.last_name }}, {{ song.composer.first_name }}</a></td>
            </tr>
        {% endfor %}
    </table>
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
    <br>
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url by-song %}?page={{ page_obj.previous_page_number }}"><small><em>previous</em></small></a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url by-song %}?page={{ page_obj.next_page_number }}"><small><em>next</em></small></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

repertoire/templates/repertoire/filtered_list.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Music Repertoire | Contemporary Youth Orchestra - proudly in residence at Cleveland State University</title>
    <meta name="description" content="A world-class orchestra">
    <link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.gif" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/grid.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/repertoire.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/fxns.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>
<body>
<div class="row">
    <a href="/"><div class="column grid_250" id="logo"></div></a>
    <div id="navigation">
        <navigation>
        </navigation>
    </div>
    <div id="searchbox">
        {% block search_box %}
            <form name="input" action="some_link" method="post">
                <input type="text" class="box" name="searchbox" value="Search" />
            </form>
        {% endblock %}
    </div><!--searchbox-->
</div>

<div class="row">
    <div class="column grid_738" id="repertoire-container" style="background:#fff;">
        {% block main_content %}
            <h1>CYO Repertoire</h1>
            {% for concert in repertoire_list %}
                <div><h2>{{ song.title }}</h2>
                    <table>
                        {% for concertsong in concert.concertsong_set.all %}
                            <tr>
                                <td>{{ concertsong.song.title }}</td>
                                <td>{{ concertsong.song.composer }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}

        {% endblock %}
    </div>
    <div class="column grid_242" id="sidebar">
        {%  block sidebar-common %}
            <span id="season">season</span><span id="season-number"><a href="/concerts">17</a></span>
        {% endblock %}
        <div class="row">
            <div class="column grid_242" id="sidebar-details">
                <ul>
                    {% for p in sublevel %}
                    {% endfor %}
                </ul>
                <ul>
                    {% for p in sublevel %}
                    {% endfor %}
                </ul>
                {% block sidebar %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column grid_1000" id="footer">
        {% block footer %}
            <ul>
                <li><!--TODO (stephen) fix the (c) to unicode-->©2011-2012 Contemporary Youth Orchestra |&nbsp;</li>
                <li>(216) 321-3525 |&nbsp;</li>
                <li><a href="/contact" class="hover-yellow">Contact</a> |&nbsp;</li>
                <li><a href="#" class="hover-yellow">Search</a></li>
                <li><a href="http://www.facebook.com/ContemporaryYouthOrchestra" target="_blank"><img src="{{ STATIC_URL }}images/social_facebook.png"></a></li>
                <li><a href="http://twitter.com/LizaGrossmanCYO" target="_blank"><img src="{{ STATIC_URL }}images/social_twitter.png"></a></li>
                <li><a href="http://www.youtube.com/user/CYOrchestra?feature=watch" target="_blank"><img src="{{ STATIC_URL }}images/social_youtube.png"></a></li>
                {% if user.is_authenticated %}<li> | <a href="/admin">Admin Section</a></li>{% endif %}
            </ul>
        {% endblock %}
        {% block extend-footer %}<span id="footer-extend">Contribute, <a href="/donate" target="_blank">Donate to CYO!</a></span>{% endblock %}
    </div></div>
</body>
</html>

repertoire/templates/repertoire/performer_detail.html
{% extends 'repertoire/rep_base.html' %}
{# model = Performer #}
{% autoescape off %}
        {% block main_content %}
                <div><h2>{{ performer.first_name }} {{ performer.last_name }}</h2>
                    <small><em>{{ performer.birth_year }}-{% if performer.death_year %}{{ performer.death_year }}{% else %}Current{% endif %}</em></small>
                    <br />  
                    {{ performer.bio|safe }}
                    {% if performer.song_set.all.count > 0 %}
                         <table>
                            <caption><h3>Composer:</h3></caption>
                            {% for cs in performer.song_set.all %}
                                <tr>
                                    <td><a href="{{ cs.get_absolute_url}}">{{ cs.title }}</a></td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                    {% if performer.arranger.all.count > 0 %}
                    <br>
                        <table>
                            <caption><h3>Arranger:</h3></caption>
                            {% for ps in performer.arranger.all %}
                                    <tr>
                                        <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                        <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                                    </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                    {% if performer.conductor.all.count > 0 %}
                    <br>
                        <table>
                            <caption><h3>Conductor:</h3></caption>
                            {% for ps in performer.conductor.all %}
                                    <tr>
                                        <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                        <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                                    </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                    {# TODO queryset in advance to grab concerts where performer was featured artist - right now this will appear occasionally when the performer wasn't #}
                    {% if performer.performedsong_set.all.count > 0 %}
                    <br>
                        <table>
                            <th><h3>Featured Artist:</h3></th>
                            {% for ps in performer.performedsong_set.all %}
                                {% if ps.concert.featured_artist == performer %}
                                    <tr>
                                        <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                        <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </table>
                    {% endif %}
                    {% if performer.guest_artist.all.count > 0 %}
                    <br>
                        <table>
                            <caption><h3>Guest Artist:</h3></caption>
                            {% for ps in performer.guest_artist.all %}
                                    <tr>
                                        <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                        <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                                    </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                    {% if performer.soloist.all.count > 0 %}
                    <br>
                        <table>
                            <caption><h3>Soloist:</h3></caption>
                            {% for ps in performer.soloist.all %}
                                    <tr>
                                        <td><a href="{{ ps.song.get_absolute_url}}">{{ ps.song.title }}</a></td>
                                        <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                                    </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                </div>
        {% endblock %}
{% endautoescape %}

repertoire/templates/repertoire/rep_base.html
<div class="full repertoire" style="float:left; margin-left:20px">
{% block rep_nav %}
    <div class="rep-nav"><strong>View by:</strong>
        <a href="{% url by-default %}">Concert</a>, <a href="{% url by-song %}">Song</a>, <a href="{% url by-composer %}">Composer</a>, <a href="{% url by-premiere %}">Premieres</a>
    </div>
{% endblock %}

<h1>CYO Repertoire</h1>
{% block main_content %}
{% endblock %}
</div>

repertoire/templates/repertoire/song_detail.html
{% extends 'repertoire/rep_base.html' %}
{# model = Song #}
        {% block main_content %}
                <div><h2>{{ song.title }}</h2>
                    <h3>Composer: <a href="{{ song.composer.get_absolute_url }}">{{ song.composer.first_name }} {{ song.composer.last_name }}</a></h3>
                    <br />
                    {{ song.description|linebreaks }}
                    <table>
                    	<th><h3>Performed During:</h3></th>
                        {% for ps in song.performedsong_set.all %}
                            <tr>
                                <td><a href="{{ ps.concert.get_absolute_url}}">{{ ps.concert.title }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
        {% endblock %}

repertoire/templates/repertoire/venue_detail.html
{% extends 'repertoire/rep_base.html' %}
{% load repertoire_tags %}
{# model = Venue #}
        {% block main_content %}
                <div><h2>{{ venue.name }}</h2>
                    {{ venue.address1 }}
                    {% if venue.address2 %}
                        <br>{{ venue.address2 }}
                    {% endif %}
                    <br>{{ venue.city }}, {{ venue.state }}  {{ venue.zip_code }}
                    <br /><br />
                    <table>
                    	<th><h2><small>Concerts Performed at {{ venue.name }}</small></h2></th>
                        {% for concert in venue.concert_set.all|order_by:'-rough_date' %}
                            <tr>
                                <td><a href="{{ concert.get_absolute_url}}">{{ concert.title }}</a></td>
                                <td>{{ concert.rough_date }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
        {% endblock %}